name: Contract Drift Detection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Validate API contracts
      env:
        BASE_URL: https://www.glowme.io
      run: |
        python3 scripts/validate_contracts.py
      timeout-minutes: 1

